# This is a basic workflow to help you get started with Actions

name: Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'      

      - name: Install npm packages - server
        run: |
          cd mern/server
          npm install       
      
      - name: Install npm packages, build then copy files - client
        run: |
          cd mern/client
          npm install
          npm run build
          cp -r ./build ../server/public
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: mern-app
          path: mern/server
        
