# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Testing
    strategy:
      matrix:
        node-version: [14.x , 16.x]
      max-parallel: 1  
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'      

      - name: Install npm packages - server
        run: |
          cd mern/server
          npm install       
      
      - name: Install npm packages, build then copy files - client
        run: |
          cd mern/client
          npm install
          npm run build
          cp -r ./build ../server/public
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: mern-app
          path: mern/server
        
